version: "3.7"

services:
  db:
    image: mariadb:10.5.8
    volumes:
      - todo-mysql-data:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint=initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ShopList
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  todo-mysql-data: null
