version: "3.7"

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - AuthOptions__ISSUER=ShopListMVCBackend20210615
      - AuthOptions__AUDIENCE=ShopListReactNative20210615
      - AuthOptions__JWTKEY=awwwwwwwwwwesome_jwt_secret_key20210615
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ShopList

volumes:
  todo-mysql-data: