version: "3.7"

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ShopList
    ports:
      - "3306"
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysqldb

volumes:
  todo-mysql-data: null
