version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ShopList

volumes:
  todo-mysql-data: